# File: mini_insta/migrations/0001_initial.py
# Author: Sung Tae Hwang (sthwang@bu.edu), 9/28/2026
# Description: Create the initial Profile database table.

# Generated by Django 6.1.1 on 2026-09-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    """Create the initial Profile database table."""

    initial = True

    # Run this migration after its listed dependencies.
    dependencies = [
    ]

    # Apply these changes to the database schema.
    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('username', models.TextField(blank=True)),
                ('display_name', models.TextField(blank=True)),
                ('profile_image_url', models.URLField(blank=True)),
                ('bio_text', models.TextField(blank=True)),
                ('join_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
