# File: mini_insta/migrations/0002_alter_profile_join_date.py
# Name: Sung Tae Hwang
# BU Email: sthwang@bu.edu
# Description: Keep each profile join date unchanged after creation.

# Generated by Django 6.1.1 on 2026-09-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
