# File: mini_insta/migrations/0002_alter_profile_join_date.py
# Author: Sung Tae Hwang (sthwang@bu.edu), 9/28/2026
# Description: Keep the profile join date fixed after creation.

# Generated by Django 6.1.1 on 2026-09-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    """Keep the profile join date fixed after creation."""

    # Run this migration after its listed dependencies.
    dependencies = [
        ('mini_insta', '0001_initial'),
    ]

    # Apply these changes to the database schema.
    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
