# File: mini_insta/migrations/0003_post_photo.py
# Author: Sung Tae Hwang (sthwang@bu.edu), 10/1/2026
# Description: Create the Post and Photo database tables.

# Generated by Django 6.1.1 on 2026-10-01 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create the Post and Photo database tables."""

    # Run this migration after its listed dependencies.
    dependencies = [
        ('mini_insta', '0002_alter_profile_join_date'),
    ]

    # Apply these changes to the database schema.
    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('caption', models.TextField()),
                ('profile', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='mini_insta.profile',
                )),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('image_url', models.URLField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='mini_insta.post',
                )),
            ],
        ),
    ]
