# File: mini_insta/migrations/0004_alter_post_caption.py
# Author: Sung Tae Hwang (sthwang@bu.edu), 10/1/2026
# Description: Allow posts to have an empty caption.

# Generated by Django 6.1.1 on 2026-10-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    """Allow posts to have an empty caption."""

    # Run this migration after its listed dependencies.
    dependencies = [
        ('mini_insta', '0003_post_photo'),
    ]

    # Apply these changes to the database schema.
    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
