# Generated by Django 6.1.1 on 2026-10-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0004_alter_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='mini_insta/'),
        ),
    ]
